"""Models for AI News Service"""

from typing import TypedDict, Annotated


class SubcategoryCheckResponse(TypedDict):
    category_id: str
    subcategory_id: str
    content: str

class CategoryCheckResponse(TypedDict):
    category_id: str
    content: str

class TopicKeywordRecord(TypedDict):
    id: str
    content: Annotated[str, "This refers to the canonical topic."]
    category_id: Annotated[str, "This refers to the category id. (uuid)"]
    subcategory_id: Annotated[str | None, "This refers to the subcategory id. (uuid)"] = None


class TopicKeywordRecordFields(TypedDict):
    category_id: str
    subcategory_id: str | None = None


class TopicKeywordRecordResponse(TypedDict):
    _id: str
    _score: float
    fields: TopicKeywordRecordFields


class PrimaryCategoryRecord(TypedDict):
    id: str
    content: Annotated[str, "This refers to the content generated by the AI for high quality retrieval. (this will be vectorized.)"]
    topic: Annotated[str, "This refers to the subcategory title."]
    category_id: Annotated[str, "This refers to the category id. (uuid)"]
    subcategory_id: Annotated[str, "This refers to the subcategory id. (uuid)"]


class PrimaryCategoryRecordFields(TypedDict):
    category_id: str
    subcategory_id: str


class PrimaryCategoryRecordResponse(TypedDict):
    _id: str
    _score: float
    fields: PrimaryCategoryRecordFields