"""Models for AI News Service"""

from typing import TypedDict, Annotated

class CategoryResponse(TypedDict):
    category_id: str
    subcategory_id: str

class ClassificationResponse(TypedDict):
    app_defined: list[CategoryResponse]
    user_defined: list[CategoryResponse] | None = None

class PrimaryCategoryRecord(TypedDict):
    """This is the record for storing the new category/subcategory title."""
    id: str
    content: Annotated[str, "This refers to the content generated by the AI for high quality retrieval. (this will be vectorized.)"]
    topic: Annotated[str, "This refers to the subcategory title."]
    category_id: Annotated[str, "This refers to the category id. (uuid)"]
    subcategory_id: Annotated[str, "This refers to the subcategory id. (uuid)"]

class TopicKeywordRecord(TypedDict):
    """This is the record for storing the canonical topic."""
    id: str
    content: Annotated[str, "This refers to the canonical topic."]
    score: float
    category_id: Annotated[str, "This refers to the category id. (uuid)"]
    subcategory_id: Annotated[str | None, "This refers to the subcategory id. (uuid)"] = None


class SubcategoryCheckResponse(TypedDict):
    category_id: str
    subcategory_id: str
    content: str

class CategoryCheckResponse(TypedDict):
    category_id: str
    content: str

class TopicKeywordRecordFields(TypedDict):
    category_id: str
    subcategory_id: str | None = None


class TopicKeywordRecordResponse(TypedDict):
    _id: str
    _score: float
    fields: TopicKeywordRecordFields


class PrimaryCategoryRecordFields(TypedDict):
    category_id: str
    subcategory_id: str


class PrimaryCategoryRecordResponse(TypedDict):
    _id: str
    _score: float
    fields: PrimaryCategoryRecordFields