"""Models for AI News Service"""
from pydantic import BaseModel, Field
import uuid
from typing import Annotated

class AiClassificationResponse(BaseModel):
    is_valid: bool
    category: str

class VDBClassificationResponse(BaseModel):
    category_id: str
    subcategory_id: str 

class NewsTitleClassificationRecord(BaseModel):
    """This is the record for storing the news title with its classification."""

    id: str = Field(default_factory=uuid.uuid4, alias="_id")
    content: Annotated[
        str,
        "This refers to the content generated by the AI for high quality retrieval. (this will be vectorized.)",
    ]
    category_id: Annotated[str, "This refers to the category id. (uuid)"]
    subcategory_id: Annotated[str, "This refers to the subcategory id. (uuid)"]


class CategoryResponse(BaseModel):
    category_id: str
    subcategory_id: str

class RelevantNewsTitlesResponse(BaseModel):
    _id: str
    _score: float
    fields: CategoryResponse
