"""enum creating

Revision ID: 07a30f4dd056
Revises: ff8991e03061
Create Date: 2026-01-02 22:51:34.971350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07a30f4dd056'
down_revision: Union[str, Sequence[str], None] = 'ff8991e03061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_source', 'articles', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_source', table_name='articles')
    # ### end Alembic commands ###
