"""Fixed name of the fields

Revision ID: 16a322580279
Revises: 4a3fac3a1857
Create Date: 2025-12-01 20:21:13.136749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16a322580279'
down_revision: Union[str, Sequence[str], None] = '4a3fac3a1857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("news_categories", "id", new_column_name="category_id")
    op.alter_column("news_subcategories", "id", new_column_name="subcategory_id")
    op.alter_column("user_subcategories", "sub_category_id", new_column_name="subcategory_id")

    op.drop_constraint(op.f('anthropic_articles_subcategory_id_fkey'), 'anthropic_articles', type_='foreignkey')
    op.drop_constraint(op.f('anthropic_articles_category_id_fkey'), 'anthropic_articles', type_='foreignkey')
    op.create_foreign_key(None, 'anthropic_articles', 'news_categories', ['category_id'], ['category_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'anthropic_articles', 'news_subcategories', ['subcategory_id'], ['subcategory_id'], ondelete='SET NULL')
    op.drop_constraint(op.f('google_articles_category_id_fkey'), 'google_articles', type_='foreignkey')
    op.drop_constraint(op.f('google_articles_subcategory_id_fkey'), 'google_articles', type_='foreignkey')
    op.create_foreign_key(None, 'google_articles', 'news_categories', ['category_id'], ['category_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'google_articles', 'news_subcategories', ['subcategory_id'], ['subcategory_id'], ondelete='SET NULL')
    
    op.drop_constraint(op.f('news_subcategories_category_id_fkey'), 'news_subcategories', type_='foreignkey')
    op.create_foreign_key(None, 'news_subcategories', 'news_categories', ['category_id'], ['category_id'], ondelete='CASCADE')
    
    op.drop_constraint(op.f('openai_articles_category_id_fkey'), 'openai_articles', type_='foreignkey')
    op.drop_constraint(op.f('openai_articles_subcategory_id_fkey'), 'openai_articles', type_='foreignkey')
    op.create_foreign_key(None, 'openai_articles', 'news_subcategories', ['subcategory_id'], ['subcategory_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'openai_articles', 'news_categories', ['category_id'], ['category_id'], ondelete='SET NULL')
    op.drop_constraint(op.f('user_categories_category_id_fkey'), 'user_categories', type_='foreignkey')
    op.create_foreign_key(None, 'user_categories', 'news_categories', ['category_id'], ['category_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_subcategories_sub_category_id_fkey'), 'user_subcategories', type_='foreignkey')
    op.create_foreign_key(None, 'user_subcategories', 'news_subcategories', ['subcategory_id'], ['subcategory_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subcategories', sa.Column('sub_category_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_subcategories', type_='foreignkey')
    op.create_foreign_key(op.f('user_subcategories_sub_category_id_fkey'), 'user_subcategories', 'news_subcategories', ['sub_category_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_subcategories', 'subcategory_id')
    op.drop_constraint(None, 'user_categories', type_='foreignkey')
    op.create_foreign_key(op.f('user_categories_category_id_fkey'), 'user_categories', 'news_categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'openai_articles', type_='foreignkey')
    op.drop_constraint(None, 'openai_articles', type_='foreignkey')
    op.create_foreign_key(op.f('openai_articles_subcategory_id_fkey'), 'openai_articles', 'news_subcategories', ['subcategory_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('openai_articles_category_id_fkey'), 'openai_articles', 'news_categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.add_column('news_subcategories', sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'news_subcategories', type_='foreignkey')
    op.create_foreign_key(op.f('news_subcategories_category_id_fkey'), 'news_subcategories', 'news_categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.drop_column('news_subcategories', 'subcategory_id')
    op.add_column('news_categories', sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('news_categories', 'category_id')
    op.drop_constraint(None, 'google_articles', type_='foreignkey')
    op.drop_constraint(None, 'google_articles', type_='foreignkey')
    op.create_foreign_key(op.f('google_articles_subcategory_id_fkey'), 'google_articles', 'news_subcategories', ['subcategory_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('google_articles_category_id_fkey'), 'google_articles', 'news_categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'anthropic_articles', type_='foreignkey')
    op.drop_constraint(None, 'anthropic_articles', type_='foreignkey')
    op.create_foreign_key(op.f('anthropic_articles_category_id_fkey'), 'anthropic_articles', 'news_categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('anthropic_articles_subcategory_id_fkey'), 'anthropic_articles', 'news_subcategories', ['subcategory_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
