"""Increased varchart length

Revision ID: 18de3f8382ca
Revises: 7083007615c0
Create Date: 2025-11-27 20:35:41.964390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18de3f8382ca'
down_revision: Union[str, Sequence[str], None] = '7083007615c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('google_articles', 'guid',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.alter_column('google_articles', 'title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('google_articles', 'title',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('google_articles', 'guid',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
