"""Added added_by_users column in category and subcategory table

Revision ID: 1cb03b4b5107
Revises: bb88dc327f89
Create Date: 2025-12-04 17:45:04.676482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cb03b4b5107'
down_revision: Union[str, Sequence[str], None] = 'bb88dc327f89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_categories', sa.Column('added_by_users', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False))
    op.add_column('news_subcategories', sa.Column('added_by_users', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_subcategories', 'added_by_users')
    op.drop_column('news_categories', 'added_by_users')
    # ### end Alembic commands ###
