"""published_at to published_on

Revision ID: 219057726572
Revises: fac706baaca7
Create Date: 2025-11-26 22:17:10.590886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '219057726572'
down_revision: Union[str, Sequence[str], None] = 'fac706baaca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anthropic_articles', sa.Column('published_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('anthropic_articles', 'published_at')
    op.add_column('google_articles', sa.Column('published_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('google_articles', 'published_at')
    op.add_column('openai_articles', sa.Column('published_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('openai_articles', 'published_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('openai_articles', sa.Column('published_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('openai_articles', 'published_on')
    op.add_column('google_articles', sa.Column('published_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('google_articles', 'published_on')
    op.add_column('anthropic_articles', sa.Column('published_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('anthropic_articles', 'published_on')
    # ### end Alembic commands ###
