"""Try

Revision ID: 29384e84546f
Revises: 57efdd0a01b6
Create Date: 2025-11-30 20:22:29.253533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29384e84546f'
down_revision: Union[str, Sequence[str], None] = '57efdd0a01b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('service_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('category', postgresql.ENUM('AI_NEWS', 'NOTIFICATIONS', 'AUTOMATION', 'ANALYTICS', 'CONTENT_DELIVERY', name='service_category_enum'), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('users',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('userservices',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('is_disabled', sa.BOOLEAN(), nullable=False),
    sa.Column('tier', postgresql.ENUM('FREE', 'PREMIUM', name='service_tier_enum'), nullable=False),
    sa.Column('usage_count', sa.INTEGER(), nullable=False),
    sa.Column('usage_limit', sa.INTEGER(), nullable=True),
    sa.Column('subcribed_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'service_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userservices')
    op.drop_table('users')
    op.drop_table('services')
    # ### end Alembic commands ###
