"""changed colums name uuid to actual

Revision ID: 33023b368863
Revises: f2adcf2f3366
Create Date: 2026-01-05 22:52:55.191391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33023b368863'
down_revision: Union[str, Sequence[str], None] = 'f2adcf2f3366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('articles_category_id_fkey'), 'articles', type_='foreignkey')
    op.drop_constraint(op.f('articles_subcategory_id_fkey'), 'articles', type_='foreignkey')
    op.drop_constraint(op.f('user_categories_category_id_fkey'), 'user_categories', type_='foreignkey')
    op.drop_constraint(op.f('news_subcategories_category_id_fkey'), 'news_subcategories', type_='foreignkey')
    op.drop_constraint(op.f('user_subcategories_subcategory_id_fkey'), 'user_subcategories', type_='foreignkey')

    op.alter_column('news_categories', 'uuid', new_column_name='category_id')
    op.alter_column('news_subcategories', 'uuid', new_column_name='subcategory_id')

    op.create_foreign_key(None, 'articles', 'news_categories', ['category_id'], ['category_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'articles', 'news_subcategories', ['subcategory_id'], ['subcategory_id'], ondelete='SET NULL')
    
    op.create_foreign_key(None, 'news_subcategories', 'news_categories', ['category_id'], ['category_id'], ondelete='CASCADE')

    op.create_foreign_key(None, 'user_categories', 'news_categories', ['category_id'], ['category_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_subcategories', 'news_subcategories', ['subcategory_id'], ['subcategory_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_subcategories', type_='foreignkey')
    op.create_foreign_key(op.f('user_subcategories_subcategory_id_fkey'), 'user_subcategories', 'news_subcategories', ['subcategory_id'], ['uuid'], ondelete='CASCADE')
    op.drop_constraint(None, 'user_categories', type_='foreignkey')
    op.create_foreign_key(op.f('user_categories_category_id_fkey'), 'user_categories', 'news_categories', ['category_id'], ['uuid'], ondelete='CASCADE')
    op.add_column('news_subcategories', sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'news_subcategories', type_='foreignkey')
    op.create_foreign_key(op.f('news_subcategories_category_id_fkey'), 'news_subcategories', 'news_categories', ['category_id'], ['uuid'], ondelete='CASCADE')
    op.drop_column('news_subcategories', 'subcategory_id')
    op.add_column('news_categories', sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False))
    op.drop_column('news_categories', 'category_id')
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.create_foreign_key(op.f('articles_subcategory_id_fkey'), 'articles', 'news_subcategories', ['subcategory_id'], ['uuid'], ondelete='SET NULL')
    op.create_foreign_key(op.f('articles_category_id_fkey'), 'articles', 'news_categories', ['category_id'], ['uuid'], ondelete='SET NULL')
    # ### end Alembic commands ###
