"""Added indexes in subcategory_id  field in article tables

Revision ID: 456e98cd00e1
Revises: d3896f1292a8
Create Date: 2025-12-01 21:30:05.834069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '456e98cd00e1'
down_revision: Union[str, Sequence[str], None] = 'd3896f1292a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_anthropic_subcategory_id', 'anthropic_articles', ['subcategory_id'], unique=False)
    op.create_index('idx_google_subcategory_id', 'google_articles', ['subcategory_id'], unique=False)
    op.create_index('idx_openai_subcategory_id', 'openai_articles', ['subcategory_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_openai_subcategory_id', table_name='openai_articles')
    op.drop_index('idx_google_subcategory_id', table_name='google_articles')
    op.drop_index('idx_anthropic_subcategory_id', table_name='anthropic_articles')
    # ### end Alembic commands ###
