"""new ssubcategory_id column on articles table

Revision ID: 492975c5972f
Revises: 31fbb3861133
Create Date: 2026-04-28 10:06:08.960748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '492975c5972f'
down_revision: Union[str, Sequence[str], None] = '31fbb3861133'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('subcategory_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'articles', 'subcategories', ['subcategory_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'subcategory_id')
    # ### end Alembic commands ###
