"""Added usercategories and usersubcategories table

Revision ID: 4a3fac3a1857
Revises: bbfca812784a
Create Date: 2025-12-01 19:26:15.012127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a3fac3a1857'
down_revision: Union[str, Sequence[str], None] = 'bbfca812784a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_categories',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['news_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'category_id')
    )
    op.create_table('user_subcategories',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sub_category_id', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['sub_category_id'], ['news_subcategories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'sub_category_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_subcategories')
    op.drop_table('user_categories')
    # ### end Alembic commands ###
