"""Varchar to text in google url

Revision ID: 57efdd0a01b6
Revises: 64dd7d63b3e1
Create Date: 2025-11-27 20:45:14.430062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57efdd0a01b6'
down_revision: Union[str, Sequence[str], None] = '64dd7d63b3e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('google_articles', 'url',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('google_articles', 'url',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###
