"""Varchar to text in all

Revision ID: 64dd7d63b3e1
Revises: fdd4ed746e88
Create Date: 2025-11-27 20:42:40.852751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64dd7d63b3e1'
down_revision: Union[str, Sequence[str], None] = 'fdd4ed746e88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anthropic_articles', 'guid',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('anthropic_articles', 'title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('google_articles', 'title',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('openai_articles', 'guid',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('openai_articles', 'title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('openai_articles', 'title',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('openai_articles', 'guid',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('google_articles', 'title',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.alter_column('anthropic_articles', 'title',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('anthropic_articles', 'guid',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
