"""Increased varchart length

Revision ID: 7083007615c0
Revises: a3ef695967d4
Create Date: 2025-11-26 23:22:26.301421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7083007615c0'
down_revision: Union[str, Sequence[str], None] = 'a3ef695967d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anthropic_articles', 'guid',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('google_articles', 'guid',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('openai_articles', 'guid',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('openai_articles', 'guid',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('google_articles', 'guid',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('anthropic_articles', 'guid',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
