"""set description field to None in articles table

Revision ID: 758b733d4f1f
Revises: 77fd9c2b5181
Create Date: 2026-04-27 15:01:52.544712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '758b733d4f1f'
down_revision: Union[str, Sequence[str], None] = '77fd9c2b5181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
