"""Removed nullable = True from the markdown_content

Revision ID: 804bf3e9cf3d
Revises: b62d1c1ad855
Create Date: 2025-12-06 18:46:52.662402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '804bf3e9cf3d'
down_revision: Union[str, Sequence[str], None] = 'b62d1c1ad855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anthropic_articles', 'markdown_content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('google_articles', 'markdown_content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('hackernoon_articles', 'markdown_content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('openai_articles', 'markdown_content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('openai_articles', 'markdown_content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('hackernoon_articles', 'markdown_content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('google_articles', 'markdown_content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('anthropic_articles', 'markdown_content',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
