"""new user defined category classifcation table created

Revision ID: a9818b73dbca
Revises: f8dd9938ad02
Create Date: 2026-02-16 20:18:12.101997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9818b73dbca'
down_revision: Union[str, Sequence[str], None] = 'f8dd9938ad02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_defined_article_classification',
    sa.Column('article_id', sa.TEXT(), nullable=False),
    sa.Column('subcategory_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.guid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['news_subcategories.subcategory_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'subcategory_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_defined_article_classification')
    # ### end Alembic commands ###
