"""Added Hackernoon table and removed func.now as server default in published_on field

Revision ID: b62d1c1ad855
Revises: 1cb03b4b5107
Create Date: 2025-12-05 21:03:16.851068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b62d1c1ad855'
down_revision: Union[str, Sequence[str], None] = '1cb03b4b5107'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hackernoon_articles',
    sa.Column('guid', sa.TEXT(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('url', sa.TEXT(), nullable=False),
    sa.Column('published_on', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('markdown_content', sa.TEXT(), nullable=False),
    sa.Column('summary', sa.TEXT(), nullable=True),
    sa.Column('category_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('subcategory_id', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['news_categories.category_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['news_subcategories.subcategory_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index('idx_hackernoon_published_on', 'hackernoon_articles', ['published_on'], unique=False)
    op.create_index('idx_hackernoon_subcategory_id', 'hackernoon_articles', ['subcategory_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_hackernoon_subcategory_id', table_name='hackernoon_articles')
    op.drop_index('idx_hackernoon_published_on', table_name='hackernoon_articles')
    op.drop_table('hackernoon_articles')
    # ### end Alembic commands ###
