"""Removed services tables

Revision ID: bbfca812784a
Revises: 29384e84546f
Create Date: 2025-11-30 23:28:35.483053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bbfca812784a'
down_revision: Union[str, Sequence[str], None] = '29384e84546f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userservices')
    op.drop_table('services')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userservices',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('service_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_disabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('tier', postgresql.ENUM('FREE', 'PREMIUM', name='service_tier_enum'), autoincrement=False, nullable=False),
    sa.Column('usage_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('usage_limit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subcribed_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.uuid'], name=op.f('userservices_service_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.uuid'], name=op.f('userservices_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'service_id', name=op.f('userservices_pkey'))
    )
    op.create_table('services',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('service_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('category', postgresql.ENUM('AI_NEWS', 'NOTIFICATIONS', 'AUTOMATION', 'ANALYTICS', 'CONTENT_DELIVERY', name='service_category_enum'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uuid', name=op.f('services_pkey'))
    )
    # ### end Alembic commands ###
