"""featured_imgage for news url

Revision ID: ce6533f91638
Revises: a9818b73dbca
Create Date: 2026-04-27 10:54:46.286928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce6533f91638'
down_revision: Union[str, Sequence[str], None] = 'a9818b73dbca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('featured_image', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'featured_image')
    # ### end Alembic commands ###
