"""Added indexes in published_on field in article tables

Revision ID: d3896f1292a8
Revises: 16a322580279
Create Date: 2025-12-01 21:00:12.957616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3896f1292a8'
down_revision: Union[str, Sequence[str], None] = '16a322580279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_anthropic_published_on', 'anthropic_articles', ['published_on'], unique=False)
    op.create_index('idx_google_published_on', 'google_articles', ['published_on'], unique=False)
    op.create_index('idx_openai_published_on', 'openai_articles', ['published_on'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_openai_published_on', table_name='openai_articles')
    op.drop_index('idx_google_published_on', table_name='google_articles')
    op.drop_index('idx_anthropic_published_on', table_name='anthropic_articles')
    # ### end Alembic commands ###
