"""added composite index of published_on and subcategory_id in articleds table

Revision ID: df4de6622ec7
Revises: 492975c5972f
Create Date: 2026-04-28 10:25:10.329841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df4de6622ec7'
down_revision: Union[str, Sequence[str], None] = '492975c5972f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_publishedon_subcategory_id', 'articles', ['published_on', 'subcategory_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_publishedon_subcategory_id', table_name='articles')
    # ### end Alembic commands ###
