"""initial commit

Revision ID: f2adcf2f3366
Revises: 
Create Date: 2026-01-05 22:16:57.074386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2adcf2f3366'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_categories',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), nullable=False),
    sa.Column('added_by_users', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('users',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('news_subcategories',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), nullable=False),
    sa.Column('added_by_users', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['news_categories.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('user_categories',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['news_categories.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'category_id')
    )
    op.create_table('articles',
    sa.Column('guid', sa.TEXT(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('url', sa.TEXT(), nullable=False),
    sa.Column('source', sa.Enum('GOOGLE', 'ANTHROPIC', 'OPENAI', 'HACKERNOON', name='source_enum'), nullable=False),
    sa.Column('published_on', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('markdown_content', sa.TEXT(), nullable=True),
    sa.Column('summary', sa.TEXT(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('subcategory_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['news_categories.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['news_subcategories.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index('idx_published_on', 'articles', ['published_on'], unique=False)
    op.create_index('idx_source', 'articles', ['source'], unique=False)
    op.create_index('idx_subcategory_id', 'articles', ['subcategory_id'], unique=False)
    op.create_table('user_subcategories',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subcategory_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['subcategory_id'], ['news_subcategories.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'subcategory_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_subcategories')
    op.drop_index('idx_subcategory_id', table_name='articles')
    op.drop_index('idx_source', table_name='articles')
    op.drop_index('idx_published_on', table_name='articles')
    op.drop_table('articles')
    op.drop_table('user_categories')
    op.drop_table('news_subcategories')
    op.drop_table('users')
    op.drop_table('news_categories')
    # ### end Alembic commands ###
