"""removed not null from category id

Revision ID: f8dd9938ad02
Revises: 33023b368863
Create Date: 2026-01-07 00:07:11.587911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8dd9938ad02'
down_revision: Union[str, Sequence[str], None] = '33023b368863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'category_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'category_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
