"""Initial setup

Revision ID: fac706baaca7
Revises: 
Create Date: 2025-11-25 19:08:48.540954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fac706baaca7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_categories',
    sa.Column('id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_subcategories',
    sa.Column('id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('category_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['news_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anthropic_articles',
    sa.Column('guid', sa.VARCHAR(length=50), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('url', sa.VARCHAR(length=200), nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('markdown_content', sa.TEXT(), nullable=False),
    sa.Column('summary', sa.TEXT(), nullable=True),
    sa.Column('category_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('subcategory_id', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['news_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['news_subcategories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_table('google_articles',
    sa.Column('guid', sa.VARCHAR(length=50), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('url', sa.VARCHAR(length=200), nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('markdown_content', sa.TEXT(), nullable=False),
    sa.Column('summary', sa.TEXT(), nullable=True),
    sa.Column('category_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('subcategory_id', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['news_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['news_subcategories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_table('openai_articles',
    sa.Column('guid', sa.VARCHAR(length=50), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('url', sa.VARCHAR(length=200), nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('markdown_content', sa.TEXT(), nullable=False),
    sa.Column('summary', sa.TEXT(), nullable=True),
    sa.Column('category_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('subcategory_id', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['news_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['news_subcategories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.drop_table('openai-articles')
    op.drop_table('anthropic-articles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anthropic-articles',
    sa.Column('guid', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('markdown_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('guid', name=op.f('anthropic-articles_pkey'))
    )
    op.create_table('openai-articles',
    sa.Column('guid', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('markdown_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('guid', name=op.f('openai-articles_pkey'))
    )
    op.drop_table('openai_articles')
    op.drop_table('google_articles')
    op.drop_table('anthropic_articles')
    op.drop_table('news_subcategories')
    op.drop_table('news_categories')
    # ### end Alembic commands ###
