"""Varchar to text in guid of google

Revision ID: fdd4ed746e88
Revises: 18de3f8382ca
Create Date: 2025-11-27 20:39:14.397154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdd4ed746e88'
down_revision: Union[str, Sequence[str], None] = '18de3f8382ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('google_articles', 'guid',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('google_articles', 'guid',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    # ### end Alembic commands ###
