"""single source of articles created

Revision ID: ff8991e03061
Revises: 804bf3e9cf3d
Create Date: 2026-01-02 21:55:20.251728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff8991e03061'
down_revision: Union[str, Sequence[str], None] = '804bf3e9cf3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('guid', sa.TEXT(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('url', sa.TEXT(), nullable=False),
    sa.Column('source', postgresql.ENUM(name='source_enum'), nullable=False),
    sa.Column('published_on', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('markdown_content', sa.TEXT(), nullable=True),
    sa.Column('summary', sa.TEXT(), nullable=True),
    sa.Column('category_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('subcategory_id', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['news_categories.category_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['news_subcategories.subcategory_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index('idx_published_on', 'articles', ['published_on'], unique=False)
    op.create_index('idx_source', 'articles', ['source'], unique=False)
    op.create_index('idx_subcategory_id', 'articles', ['subcategory_id'], unique=False)
    op.drop_index(op.f('idx_google_published_on'), table_name='google_articles')
    op.drop_index(op.f('idx_google_subcategory_id'), table_name='google_articles')
    op.drop_table('google_articles')
    op.drop_index(op.f('idx_anthropic_published_on'), table_name='anthropic_articles')
    op.drop_index(op.f('idx_anthropic_subcategory_id'), table_name='anthropic_articles')
    op.drop_table('anthropic_articles')
    op.drop_index(op.f('idx_openai_published_on'), table_name='openai_articles')
    op.drop_index(op.f('idx_openai_subcategory_id'), table_name='openai_articles')
    op.drop_table('openai_articles')
    op.drop_index(op.f('idx_hackernoon_published_on'), table_name='hackernoon_articles')
    op.drop_index(op.f('idx_hackernoon_subcategory_id'), table_name='hackernoon_articles')
    op.drop_table('hackernoon_articles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hackernoon_articles',
    sa.Column('guid', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('published_on', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('markdown_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('subcategory_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['news_categories.category_id'], name=op.f('hackernoon_articles_category_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['news_subcategories.subcategory_id'], name=op.f('hackernoon_articles_subcategory_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('guid', name=op.f('hackernoon_articles_pkey'))
    )
    op.create_index(op.f('idx_hackernoon_subcategory_id'), 'hackernoon_articles', ['subcategory_id'], unique=False)
    op.create_index(op.f('idx_hackernoon_published_on'), 'hackernoon_articles', ['published_on'], unique=False)
    op.create_table('openai_articles',
    sa.Column('guid', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('markdown_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('subcategory_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('published_on', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['news_categories.category_id'], name=op.f('openai_articles_category_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['news_subcategories.subcategory_id'], name=op.f('openai_articles_subcategory_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('guid', name=op.f('openai_articles_pkey'))
    )
    op.create_index(op.f('idx_openai_subcategory_id'), 'openai_articles', ['subcategory_id'], unique=False)
    op.create_index(op.f('idx_openai_published_on'), 'openai_articles', ['published_on'], unique=False)
    op.create_table('anthropic_articles',
    sa.Column('guid', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('markdown_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('subcategory_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('published_on', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['news_categories.category_id'], name=op.f('anthropic_articles_category_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['news_subcategories.subcategory_id'], name=op.f('anthropic_articles_subcategory_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('guid', name=op.f('anthropic_articles_pkey'))
    )
    op.create_index(op.f('idx_anthropic_subcategory_id'), 'anthropic_articles', ['subcategory_id'], unique=False)
    op.create_index(op.f('idx_anthropic_published_on'), 'anthropic_articles', ['published_on'], unique=False)
    op.create_table('google_articles',
    sa.Column('guid', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('markdown_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('subcategory_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('published_on', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['news_categories.category_id'], name=op.f('google_articles_category_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['news_subcategories.subcategory_id'], name=op.f('google_articles_subcategory_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('guid', name=op.f('google_articles_pkey'))
    )
    op.create_index(op.f('idx_google_subcategory_id'), 'google_articles', ['subcategory_id'], unique=False)
    op.create_index(op.f('idx_google_published_on'), 'google_articles', ['published_on'], unique=False)
    op.drop_index('idx_subcategory_id', table_name='articles')
    op.drop_index('idx_source', table_name='articles')
    op.drop_index('idx_published_on', table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###
